name: README to mdBook

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Prepare mdBook with only README
        run: |
          mkdir -p book/src
          cp README.md book/src/README.md
          echo "# Summary\n\n- [Project README](README.md)" > book/src/SUMMARY.md

      - name: Build book
        run: mdbook build book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: book/book
